set nobackup
set showmatch
set list
set listchars=tab:->,trail:_
set expandtab
set title
set tabstop=8
set shiftwidth=4
set softtabstop=4
set autoindent
set smartindent
set clipboard=unnamed
set wrap
set backspace=indent,eol,start
syntax on
filetype plugin indent on

" NERDTree
" Toggle を <C-n> にバインド
map <C-n> :NERDTreeToggle<CR>
" Vim 起動時に自動でファイルビューアーを開く
autocmd vimenter * NERDTree | wincmd p
" Q. How can I close vim if the only window left open is a NERDTree?
" A. Stick this in your vimrc:
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
" config for golang
autocmd FileType go setlocal noexpandtab shiftwidth=8 softtabstop=8
" config for python
set omnifunc=pythoncomplete#Complete
" config for rustfmt
let g:rustfmt_autosave = 1
" config syntastic
" set statusline+=%#warningmsg#
" set statusline+=%{SyntasticStatuslineFlag()}
" set statusline+=%*
" 
" let g:syntastic_always_populate_loc_list = 1
" let g:syntastic_auto_loc_list = 1
" let g:syntastic_check_on_open = 1
" let g:syntastic_check_on_wq = 0

colorscheme molokai
set t_Co=256
