set nobackup
set showmatch
set list
set listchars=tab:->,trail:_
set expandtab
set title
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set smartindent
set clipboard=unnamed
set wrap
set backspace=indent,eol,start
syntax on
filetype plugin indent on
colorscheme molokai
set t_Co=256
