[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'w0rp/ale'
hook_post_source = '''
  let g:ale_linters = {
\   'python': ['pylint'],
\}
  let g:ale_sign_error = '>>'
  let g:ale_sign_warning = '--'
  let g:ale_python_pylint_executable = 'python3'
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_post_source = '''
let g:quickrun_config={'_': {'split': 'vertical'}}
'''

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'hotwatermorning/auto-git-diff'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = '''
let g:memolist_memo_suffix = "md"
let g:memolist_ex_cmd = 'NERDTree'
'''
